// Code generated by flop-gen. DO NOT EDIT.

export const flopLayouts = [
  {
    "path": "/",
    "entry": "./pages/layout.tsx"
  }
] as const;

export const flopPages = [
  {
    "path": "/",
    "entry": "./pages/home.tsx"
  },
  {
    "path": "/post/:slug",
    "entry": "./pages/post.tsx"
  },
  {
    "path": "/about",
    "entry": "./pages/about.tsx"
  }
] as const;
