// Code generated by flop-gen. DO NOT EDIT.

package app

type Movie struct {
	CreatedAt      *int64   `json:"createdAt,omitempty"`
	Genres         []string `json:"genres,omitempty"`
	ID             *string  `json:"id,omitempty"`
	Overview       *string  `json:"overview,omitempty"`
	Rating         *float64 `json:"rating,omitempty"`
	RuntimeMinutes *int64   `json:"runtimeMinutes,omitempty"`
	Slug           string   `json:"slug"`
	Title          string   `json:"title"`
	Votes          *int64   `json:"votes,omitempty"`
	Year           int64    `json:"year"`
}
