dev:
	cd ../.. && cd examples/movies-zig-react && zig build run

seed:
	cd ../.. && cd examples/movies-zig-react && zig build run-seed

build:
	cd ../.. && cd examples/movies-zig-react && zig build -Doptimize=ReleaseFast

run: dev