// Code generated by flop-gen. DO NOT EDIT.

package app

const (
	TableComments = "comments"
	TablePosts    = "posts"
	TableSecrets  = "secrets"
	TableUsers    = "users"
)

type TableNames struct {
	Comments string
	Posts    string
	Secrets  string
	Users    string
}

var Tables = TableNames{
	Comments: TableComments,
	Posts:    TablePosts,
	Secrets:  TableSecrets,
	Users:    TableUsers,
}
