// Code generated by flop-gen. DO NOT EDIT.

package app

import flop "github.com/marcisbee/flop"

type Comment struct {
	AuthorID  string  `json:"authorId"`
	Body      string  `json:"body"`
	CreatedAt *int64  `json:"createdAt,omitempty"`
	ID        *string `json:"id,omitempty"`
	PostID    string  `json:"postId"`
}

type Post struct {
	AuthorID      string        `json:"authorId"`
	Body          string        `json:"body"`
	CoverImage    *flop.FileRef `json:"coverImage,omitempty"`
	CreatedAt     *int64        `json:"createdAt,omitempty"`
	Excerpt       *string       `json:"excerpt,omitempty"`
	ID            *string       `json:"id,omitempty"`
	InternalNotes *string       `json:"internalNotes,omitempty"`
	Published     *bool         `json:"published,omitempty"`
	PublishedAt   *int64        `json:"publishedAt,omitempty"`
	Slug          string        `json:"slug"`
	Title         string        `json:"title"`
}

type Secret struct {
	ID    *string `json:"id,omitempty"`
	Key   string  `json:"key"`
	Value string  `json:"value"`
}

type User struct {
	Email    string   `json:"email"`
	ID       *string  `json:"id,omitempty"`
	Name     string   `json:"name"`
	Password string   `json:"password"`
	Roles    []string `json:"roles,omitempty"`
}
